name: decidenet
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - backcall=0.1.0=py38_0
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28=py38_0
  - decorator=4.4.1=py_0
  - ipykernel=5.1.4=py38h39e3cac_0
  - ipython=7.12.0=py38h5ca1d4c_0
  - ipython_genutils=0.2.0=py38_0
  - jedi=0.16.0=py38_0
  - jupyter_client=5.3.4=py38_0
  - jupyter_core=4.6.1=py38_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - ncurses=6.1=he6710b0_1
  - openssl=1.1.1d=h7b6447c_4
  - parso=0.6.1=py_0
  - pexpect=4.8.0=py38_0
  - pickleshare=0.7.5=py38_1000
  - pip=20.0.2=py38_1
  - prompt_toolkit=3.0.3=py_0
  - pygments=2.5.2=py_0
  - python=3.8.1=h0371630_1
  - python-dateutil=2.8.1=py_0
  - readline=7.0=h7b6447c_5
  - setuptools=45.2.0=py38_0
  - six=1.14.0=py38_0
  - sqlite=3.31.1=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - tornado=6.0.3=py38h7b6447c_3
  - traitlets=4.3.3=py38_0
  - wcwidth=0.1.8=py_0
  - wheel=0.34.2=py38_0
  - xz=5.2.4=h14c3975_4
  - zeromq=4.3.1=he6710b0_3
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - bids-validator==1.4.2
    - bleach==3.1.0
    - cycler==0.10.0
    - defusedxml==0.6.0
    - docopt==0.6.2
    - entrypoints==0.3
    - ipython-genutils==0.2.0
    - jinja2==2.11.1
    - joblib==0.14.1
    - json5==0.9.1
    - jsonschema==3.2.0
    - jupyter-core==4.6.2
    - jupyterlab==1.2.6
    - jupyterlab-server==1.0.6
    - kiwisolver==1.1.0
    - markupsafe==1.1.1
    - matplotlib==3.1.3
    - mistune==0.8.4
    - nbconvert==5.6.1
    - nbformat==5.0.4
    - nibabel==3.0.1
    - nilearn==0.6.1
    - nistats==0.0.1b1
    - notebook==6.0.3
    - num2words==0.5.10
    - numpy==1.18.1
    - pandas==1.0.1
    - pandocfilters==1.4.2
    - patsy==0.5.1
    - prometheus-client==0.7.1
    - ptyprocess==0.6.0
    - pybids==0.10.0
    - pyparsing==2.4.6
    - pyrsistent==0.15.7
    - pytz==2019.3
    - pyzmq==18.1.1
    - scikit-learn==0.22.1
    - scipy==1.4.1
    - send2trash==1.5.0
    - sklearn==0.0
    - sqlalchemy==1.3.13
    - terminado==0.8.3
    - testpath==0.4.4
    - webencodings==0.5.1
prefix: /home/kmb/anaconda3/envs/decidenet

